### ISSUE TITLE
Build fails on ARM Cortex-A9 cRIO

### ISSUE THREAD

**Issue by DavidStaab** [featherweight/ftw-kernel#3]
Here's the last block of output from `./build-ftw.sh`. Looks like `link` failed because of poorly structured arguments?

https://gist.github.com/DavidStaab/b0f5b97f3c29d79e2fe5

**Comment by wirebirdlabs** [comment]
Looking into this ...

**Comment by DavidStaab** [comment]
Working as of commit 6a37aaecc20f089a44600414ad9047b69470e3a3

Close this one?

**Comment by wirebirdlabs** [comment]
sounds good to me! there may be more issues, but we can file these as separate, focused issues.

**Comment by wirebirdlabs** [comment]
@DavidStaab, can you test with the most up-to-date versions of both ftw-kernel (https://github.com/featherweight/ftw-kernel/commits/master) and featherweight (https://github.com/featherweight/featherweight/commit/0337a16bee124f401d3f5a8073fa7593557ae3b5)?

Note that after building ftw-kernel, you'll need to manually rename and move it to `/usr/lib/libftw.so.0.7.0`

It appears that most of the tests are now running, except for a few of the Reflection tests with higher-order arrays of DSHandle non-fixed length types ....

**Comment by DavidStaab** [comment]
Yes, it's working now. Sorry for the delayed response here; still learning to navigate github's notification system.

**Comment by wirebirdlabs** [comment]
> delayed response here

Same here, and no worries! Glad it's working. I'm looking into how to change the build script to support [SOVERSION](https://cmake.org/cmake/help/v2.8.12/cmake.html#prop_tgt:SOVERSION) to properly version the shared library filename. Also, looking into some low-barrier techniques for copying the library into `/usr/lib/` part of the build process (perhaps, as a shell script, rather than from within the CMake script itself, which would be kinda dirty).

The general problem statement here "deploying this shared library to a RIO target, both during development and in production" is one that I'm personally unlikely to try to tackle as a short-term priority; this will be an opportunity for others to contribute if they have a more urgent need.

Closing this issue ...

**Comment by DavidStaab** [comment]
FWIW, I learned that `/usr/lib` is not the right place to put this binary, especially not without the use of a package manager. A better location is `/usr/local` (i.e. `/usr/local/lib`).

**Comment by wirebirdlabs** [comment]
This jives with what I observe and reckon as well.

It's also the packaging default destination when adding:

```CMake
set (CPACK_PACKAGE_NAME ${PROJECT_NAME})
include (CPack)
```

to the CMake build script. This is in direct contrast to where all the other NI toolkits are installed -- within `/usr/lib/`.

This line (see link) would not even be necessary; it's just there currently to conform to the observed pattern of putting dependencies such as this into `/usr/lib/`: https://github.com/featherweight/ftw-kernel/commit/d42c5479dac1110549a69ee3145c1cc87ff2c25a#diff-af3b638bc2a3e6c650974192a53c7291L153

Which is correct? This falls under that umbrella of deployment considerations where I don't have the time to spend right now, but it ought to be designed intentionally and correctly eventually.
